---
title: "Restarting and Clearing"
author: "Jose Francisco Endrinal"
date: "February 18, 2018"
output: github_document
---

## Introduction

I'm trying so hard to get people on the bandwagon of clearing and restarting their R sessions frequently. If there's anything you can do to ensure the integrity of your code, it's restarting the R session, clearing your console screen, and re-running your code.  

This practice ensures that you always start from a clean slate when you run your analysis. If you start your analysis with objects in your workspace and your code relies on that workspace, chances are that your analysis will fail to deliver, or you get unexpected (often wrong) results from the code you just run.  

## Restarting

Restarting begins your R session as if nothing ever happened and deletes all the objects you have in your workspace. Basically, you start with a clean slate.    

If you're on rstudio you can use the `.rs.restartR()` command in the console or use the following Keyboard shortcuts depending on your OS:  

`Ctrl+Shift+F10` for Windows and Linux  
`Command+Shift+F10` for MacOS

#### Why this is important

#### An Example



## Clearing

Clearing your console keeps the distractions away. Basically you start with a clear screen, but you do not delete your environment objects.

#### Why this is important

#### An example